### PR TITLE
Update runtime to 44 and other fixes

### PR DESCRIPTION
**Pull request by bbhtt**
Closes https://github.com/flathub/org.gnome.gitg/issues/25
Closes https://github.com/flathub/org.gnome.gitg/issues/24
Addresses https://github.com/flathub/org.gnome.gitg/issues/23

If you want I can drop the dependency updates commit.

### CODE REVIEW

**Comment by wjt** [comment]
Works On My Machine!

**Comment by albfan** [comment]
Thanks Will review and try to merge upstream too.

A MR on main repo will be accepted too

**Comment by albfan** [comment]
Many thanks @bbhtt I just rework a few things to merge upstream too in #28

**Comment by bbhtt** [comment]
Awesome, thanks!

**Pull request closed without merging**
