### PR TITLE
Update to release gitg 41

### PR DESCRIPTION
**Pull request by albfan**

### CODE REVIEW

**Comment by hfiguiere** [comment]
thea appstream doesn't seem to be installed.

**Comment by hfiguiere** [comment]
The thing is there is one upstream
And it apparently is installed.
https://gitlab.gnome.org/GNOME/gitg/-/blob/v41/data/meson.build

That's what should be solved.

**Comment by albfan** [comment]
@hfiguiere I see some warnings on gitg build about i18n. Looks it do not install on metainfo, so https://github.com/flathub/org.gnome.gitg/pull/20/commits/f209f14e36c67de596d22dee5c6276abd8e94128 fixes it

Let's see if I figure out the problem

**Comment by albfan** [comment]
@bilelmoussaoui figure out, I was removing metainfo on cleaning step

**Pull request merged**
