### PR TITLE
Update dependencies and runtime

### PR DESCRIPTION
**Pull request by Eonfge**

### CODE REVIEW

**Comment by bbhtt** [comment]
Peas-2.0 breaks API/ABI https://gnome.pages.gitlab.gnome.org/libpeas/libpeas-2/migrating-1to2.html I think the x-checker should be restricted to <=1.x, not sure if peas-1.0 will get anymore releases though.

**Comment by bbhtt** [comment]
Hi @Eonfge do you still want to work on this? You need to add gtksourceview4 to the manifest.

**Comment by Eonfge** [comment]
I'm not too enthusiastic about this package, but I'll gladly copy-paste a module so that this package compiles

**Comment by bbhtt** [comment]
```
ERROR: Target 'gitg-1.0' has 1 outputs: ['libgitg-1.0.so.0.0.0'], but only 4 "install_dir"s were found.
```

This is a meson bug, that is not in the GNOME runtime iirc.

**Comment by bbhtt** [comment]
Need to wait for an update in the GNOME SDK

**Comment by bbhtt** [comment]
Should be in now

bot, build

**Comment by bbhtt** [comment]
Hrm the update is published but the buildserver is not using it, probably some cache issue. Will try later. meson 1.2.3 should be the fixed version it is still using 1.2.1

```
flatpak run --command=sh org.gnome.Sdk//45                                   
[📦 org.gnome.Sdk ~]$ meson --version
1.2.3
```

**Comment by bbhtt** [comment]
bot, build

**Comment by bbhtt** [comment]
There is an infra snag on the flathub runners preventing the Sdk from being updated, I've pinged the admins.

**Comment by albfan** [comment]
See gitg builds working again would be great.

**Comment by bbhtt** [comment]
bot, build

**Comment by bbhtt** [comment]
There should be fine

**Comment by Eonfge** [comment]
It works. This was a lot of work on your end but thanks for seeing it through!

**Pull request merged**
